### ISSUE TITLE
Bert_Search_Web Fails to start

### ISSUE THREAD

**Issue by ssanjoris** [Hironsan/bertsearch#33]
I followed the steps provided and made changes suggested in the reported issues, I am getting the following Error
Can you please look into this.
 
```bash
arch_bertserving_1
unifidata@bertsearch-unifidata-ubuntu:~$ sudo docker logs bertsearch_web_1
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from flask import Flask, render_template, jsonify, request
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/site-packages/jinja2/__init__.py)
```

Your Environment
---------

*   Operating System: Ubuntu 20.04.4
*   Python Version: 3.8.10

**Comment by ShawnNew** [comment]
just update Flask version in web/requirements.txt, let's say Flask==2.0.0

**Comment by ssanjoris** [comment]
> just update Flask version in web/requirements.txt, let's say Flask==2.0.0

Hi .. Thank you it worked .... There was another problem .. there is a version conflict in bert's server and client...
I made sure bert-serving-client is 1.9.8 matching with the server.. Now the dockers are up and running running.

But, I do not think that, GUI search is giving expected result.. I do not see any errors in the logs.
How to verify that, the model provided is correct..

Thanks in advance!

**Comment by ShawnNew** [comment]
> > just update Flask version in web/requirements.txt, let's say Flask==2.0.0
> 
> Hi .. Thank you it worked .... There was another problem .. there is a version conflict in bert's server and client... I made sure bert-serving-client is 1.9.8 matching with the server.. Now the dockers are up and running running.
> 
> But, I do not think that, GUI search is giving expected result.. I do not see any errors in the logs. How to verify that, the model provided is correct..
> 
> Thanks in advance!

Met the same problem, still working on it.

The only way you can debug this is by attaching to each docker container and seeing what's wrong with the service.

The bert-serving-client is now deprecated, we may want to try a new service [clip_service](https://github.com/jina-ai/clip-as-service) which is just an upgrade.

**Comment by ShawnNew** [comment]
> > > just update Flask version in web/requirements.txt, let's say Flask==2.0.0
> > 
> > 
> > Hi .. Thank you it worked .... There was another problem .. there is a version conflict in bert's server and client... I made sure bert-serving-client is 1.9.8 matching with the server.. Now the dockers are up and running running.
> > But, I do not think that, GUI search is giving expected result.. I do not see any errors in the logs. How to verify that, the model provided is correct..
> > Thanks in advance!
> 
> Met the same problem, still working on it.
> 
> The only way you can debug this is by attaching to each docker container and seeing what's wrong with the service.
> 
> The bert-serving-client is now deprecated, we may want to try a new service [clip_service](https://github.com/jina-ai/clip-as-service) which is just an upgrade.

For whom is interested in this problem, please refer to this #34
