### ISSUE TITLE
unable to run docker-compose

### ISSUE THREAD

**Issue by helloworldkr** [Hironsan/bertsearch#8]
Getting the following error , am i missing some step:

WARNING: The PATH_MODEL variable is not set. Defaulting to a blank string.
Building bertserving
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 360, in ensure_image_exists
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 260, in build
  File "site-packages/docker/api/build.py", line 307, in _set_auth_headers
  File "site-packages/docker/auth.py", line 310, in get_all_credentials
  File "site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/dockerpycreds/store.py", line 25, in __init__
dockerpycreds.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
[18955] Failed to execute script docker-compose

**Comment by Hironsan** [comment]
Please specify `PATH_MODEL` as an environment variable.

**Comment by helloworldkr** [comment]
I have added the PATH_MODEL as described in the instructions:

![Selection_002](https://user-images.githubusercontent.com/9402190/69488950-71c7ee00-0e97-11ea-8af7-eb90b831ccb7.png)
